/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ForslagRouteImport } from './routes/forslag'
import { Route as LaggTillRouteImport } from './routes/lagg-till'
import { Route as SokRouteImport } from './routes/sok'
import { Route as BokIdRouteImport } from './routes/bok.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForslagRoute = ForslagRouteImport.update({
  id: '/forslag',
  path: '/forslag',
  getParentRoute: () => rootRouteImport,
} as any)
const LaggTillRoute = LaggTillRouteImport.update({
  id: '/lagg-till',
  path: '/lagg-till',
  getParentRoute: () => rootRouteImport,
} as any)
const SokRoute = SokRouteImport.update({
  id: '/sok',
  path: '/sok',
  getParentRoute: () => rootRouteImport,
} as any)
const BokIdRoute = BokIdRouteImport.update({
  id: '/bok/$id',
  path: '/bok/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forslag': typeof ForslagRoute
  '/lagg-till': typeof LaggTillRoute
  '/sok': typeof SokRoute
  '/bok/$id': typeof BokIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forslag': typeof ForslagRoute
  '/lagg-till': typeof LaggTillRoute
  '/sok': typeof SokRoute
  '/bok/$id': typeof BokIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forslag': typeof ForslagRoute
  '/lagg-till': typeof LaggTillRoute
  '/sok': typeof SokRoute
  '/bok/$id': typeof BokIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/forslag' | '/lagg-till' | '/sok' | '/bok/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/forslag' | '/lagg-till' | '/sok' | '/bok/$id'
  id: '__root__' | '/' | '/forslag' | '/lagg-till' | '/sok' | '/bok/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForslagRoute: typeof ForslagRoute
  LaggTillRoute: typeof LaggTillRoute
  SokRoute: typeof SokRoute
  BokIdRoute: typeof BokIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forslag': {
      id: '/forslag'
      path: '/forslag'
      fullPath: '/forslag'
      preLoaderRoute: typeof ForslagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lagg-till': {
      id: '/lagg-till'
      path: '/lagg-till'
      fullPath: '/lagg-till'
      preLoaderRoute: typeof LaggTillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sok': {
      id: '/sok'
      path: '/sok'
      fullPath: '/sok'
      preLoaderRoute: typeof SokRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bok/$id': {
      id: '/bok/$id'
      path: '/bok/$id'
      fullPath: '/bok/$id'
      preLoaderRoute: typeof BokIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForslagRoute: ForslagRoute,
  LaggTillRoute: LaggTillRoute,
  SokRoute: SokRoute,
  BokIdRoute: BokIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
